// This file is generated by a tool, from the `languageCodez.tsv` file in this repository
namespace Whisper
{
	/// <summary>Supported languages</summary>
	public enum eLanguage: uint
	{
		/// <summary>Afrikaans</summary>
		Afrikaans = 0x6661,
		/// <summary>Albanian</summary>
		Albanian = 0x7173,
		/// <summary>Amharic</summary>
		Amharic = 0x6D61,
		/// <summary>Arabic</summary>
		Arabic = 0x7261,
		/// <summary>Armenian</summary>
		Armenian = 0x7968,
		/// <summary>Assamese</summary>
		Assamese = 0x7361,
		/// <summary>Azerbaijani</summary>
		Azerbaijani = 0x7A61,
		/// <summary>Bashkir</summary>
		Bashkir = 0x6162,
		/// <summary>Basque</summary>
		Basque = 0x7565,
		/// <summary>Belarusian</summary>
		Belarusian = 0x6562,
		/// <summary>Bengali</summary>
		Bengali = 0x6E62,
		/// <summary>Bosnian</summary>
		Bosnian = 0x7362,
		/// <summary>Breton</summary>
		Breton = 0x7262,
		/// <summary>Bulgarian</summary>
		Bulgarian = 0x6762,
		/// <summary>Catalan</summary>
		Catalan = 0x6163,
		/// <summary>Chinese</summary>
		Chinese = 0x687A,
		/// <summary>Croatian</summary>
		Croatian = 0x7268,
		/// <summary>Czech</summary>
		Czech = 0x7363,
		/// <summary>Danish</summary>
		Danish = 0x6164,
		/// <summary>Dutch</summary>
		Dutch = 0x6C6E,
		/// <summary>English</summary>
		English = 0x6E65,
		/// <summary>Estonian</summary>
		Estonian = 0x7465,
		/// <summary>Faroese</summary>
		Faroese = 0x6F66,
		/// <summary>Finnish</summary>
		Finnish = 0x6966,
		/// <summary>French</summary>
		French = 0x7266,
		/// <summary>Galician</summary>
		Galician = 0x6C67,
		/// <summary>Georgian</summary>
		Georgian = 0x616B,
		/// <summary>German</summary>
		German = 0x6564,
		/// <summary>Greek</summary>
		Greek = 0x6C65,
		/// <summary>Gujarati</summary>
		Gujarati = 0x7567,
		/// <summary>Haitian Creole</summary>
		HaitianCreole = 0x7468,
		/// <summary>Hausa</summary>
		Hausa = 0x6168,
		/// <summary>Hawaiian</summary>
		Hawaiian = 0x776168,
		/// <summary>Hebrew</summary>
		Hebrew = 0x7769,
		/// <summary>Hindi</summary>
		Hindi = 0x6968,
		/// <summary>Hungarian</summary>
		Hungarian = 0x7568,
		/// <summary>Icelandic</summary>
		Icelandic = 0x7369,
		/// <summary>Indonesian</summary>
		Indonesian = 0x6469,
		/// <summary>Italian</summary>
		Italian = 0x7469,
		/// <summary>Japanese</summary>
		Japanese = 0x616A,
		/// <summary>Javanese</summary>
		Javanese = 0x776A,
		/// <summary>Kannada</summary>
		Kannada = 0x6E6B,
		/// <summary>Kazakh</summary>
		Kazakh = 0x6B6B,
		/// <summary>Khmer</summary>
		Khmer = 0x6D6B,
		/// <summary>Korean</summary>
		Korean = 0x6F6B,
		/// <summary>Lao</summary>
		Lao = 0x6F6C,
		/// <summary>Latin</summary>
		Latin = 0x616C,
		/// <summary>Latvian</summary>
		Latvian = 0x766C,
		/// <summary>Lingala</summary>
		Lingala = 0x6E6C,
		/// <summary>Lithuanian</summary>
		Lithuanian = 0x746C,
		/// <summary>Luxembourgish</summary>
		Luxembourgish = 0x626C,
		/// <summary>Macedonian</summary>
		Macedonian = 0x6B6D,
		/// <summary>Malagasy</summary>
		Malagasy = 0x676D,
		/// <summary>Malay</summary>
		Malay = 0x736D,
		/// <summary>Malayalam</summary>
		Malayalam = 0x6C6D,
		/// <summary>Maltese</summary>
		Maltese = 0x746D,
		/// <summary>Maori</summary>
		Maori = 0x696D,
		/// <summary>Marathi</summary>
		Marathi = 0x726D,
		/// <summary>Mongolian</summary>
		Mongolian = 0x6E6D,
		/// <summary>Myanmar</summary>
		Myanmar = 0x796D,
		/// <summary>Nepali</summary>
		Nepali = 0x656E,
		/// <summary>Norwegian</summary>
		Norwegian = 0x6F6E,
		/// <summary>Nynorsk</summary>
		Nynorsk = 0x6E6E,
		/// <summary>Occitan</summary>
		Occitan = 0x636F,
		/// <summary>Pashto</summary>
		Pashto = 0x7370,
		/// <summary>Persian</summary>
		Persian = 0x6166,
		/// <summary>Polish</summary>
		Polish = 0x6C70,
		/// <summary>Portuguese</summary>
		Portuguese = 0x7470,
		/// <summary>Punjabi</summary>
		Punjabi = 0x6170,
		/// <summary>Romanian</summary>
		Romanian = 0x6F72,
		/// <summary>Russian</summary>
		Russian = 0x7572,
		/// <summary>Sanskrit</summary>
		Sanskrit = 0x6173,
		/// <summary>Serbian</summary>
		Serbian = 0x7273,
		/// <summary>Shona</summary>
		Shona = 0x6E73,
		/// <summary>Sindhi</summary>
		Sindhi = 0x6473,
		/// <summary>Sinhala</summary>
		Sinhala = 0x6973,
		/// <summary>Slovak</summary>
		Slovak = 0x6B73,
		/// <summary>Slovenian</summary>
		Slovenian = 0x6C73,
		/// <summary>Somali</summary>
		Somali = 0x6F73,
		/// <summary>Spanish</summary>
		Spanish = 0x7365,
		/// <summary>Sundanese</summary>
		Sundanese = 0x7573,
		/// <summary>Swahili</summary>
		Swahili = 0x7773,
		/// <summary>Swedish</summary>
		Swedish = 0x7673,
		/// <summary>Tagalog</summary>
		Tagalog = 0x6C74,
		/// <summary>Tajik</summary>
		Tajik = 0x6774,
		/// <summary>Tamil</summary>
		Tamil = 0x6174,
		/// <summary>Tatar</summary>
		Tatar = 0x7474,
		/// <summary>Telugu</summary>
		Telugu = 0x6574,
		/// <summary>Thai</summary>
		Thai = 0x6874,
		/// <summary>Tibetan</summary>
		Tibetan = 0x6F62,
		/// <summary>Turkish</summary>
		Turkish = 0x7274,
		/// <summary>Turkmen</summary>
		Turkmen = 0x6B74,
		/// <summary>Ukrainian</summary>
		Ukrainian = 0x6B75,
		/// <summary>Urdu</summary>
		Urdu = 0x7275,
		/// <summary>Uzbek</summary>
		Uzbek = 0x7A75,
		/// <summary>Vietnamese</summary>
		Vietnamese = 0x6976,
		/// <summary>Welsh</summary>
		Welsh = 0x7963,
		/// <summary>Yiddish</summary>
		Yiddish = 0x6979,
		/// <summary>Yoruba</summary>
		Yoruba = 0x6F79,
	}
}