// This header is generated by a tool
#pragma once
#include <stdint.h>

namespace DirectCompute
{
	enum struct eComputeShader: uint16_t
	{
		add = 0,
		addInPlace = 1,
		addRepeat = 2,
		addRepeatGelu = 3,
		addRepeatScale = 4,
		addRows = 5,
		convolutionMain = 6,
		convolutionMain2 = 7,
		convolutionMain2Fixed = 8,
		convolutionPrep1 = 9,
		convolutionPrep2 = 10,
		copyConvert = 11,
		copyTranspose = 12,
		diagMaskInf = 13,
		flashAttention = 14,
		flashAttentionCompat1 = 15,
		flashAttentionCompat2 = 16,
		flashAttentionCompat3 = 17,
		fmaRepeat1 = 18,
		fmaRepeat2 = 19,
		matReshapePanels = 20,
		mulMatByRow = 21,
		mulMatByRowTiled = 22,
		mulMatByRowTiledEx = 23,
		mulMatByScalar = 24,
		mulMatDotMain = 25,
		mulMatDotReshape = 26,
		mulMatMadMain = 27,
		mulMatTiled = 28,
		mulMatTiledEx = 29,
		norm = 30,
		normCompat = 31,
		normFixed = 32,
		scaleInPlace = 33,
		softMax = 34,
		softMaxCompat = 35,
		softMaxFixed = 36,
		zeroMemory = 37,
	};

	const char* computeShaderName( eComputeShader cs );
}